package com.zhangyangyang.pojo;

public class ZyyItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.sku
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private Long sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.title
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.sell_point
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String sellPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.price
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.num
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.status
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_item.cid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private Long cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.sku
     *
     * @return the value of zyy_item.sku
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public Long getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.sku
     *
     * @param sku the value for zyy_item.sku
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setSku(Long sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.title
     *
     * @return the value of zyy_item.title
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.title
     *
     * @param title the value for zyy_item.title
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.sell_point
     *
     * @return the value of zyy_item.sell_point
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.sell_point
     *
     * @param sellPoint the value for zyy_item.sell_point
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.price
     *
     * @return the value of zyy_item.price
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.price
     *
     * @param price the value for zyy_item.price
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.num
     *
     * @return the value of zyy_item.num
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.num
     *
     * @param num the value for zyy_item.num
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.status
     *
     * @return the value of zyy_item.status
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.status
     *
     * @param status the value for zyy_item.status
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_item.cid
     *
     * @return the value of zyy_item.cid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_item.cid
     *
     * @param cid the value for zyy_item.cid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }
}