package com.zhangyangyang.pojo;

public class ZyyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_user.openid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_user.nickname
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_user.headimgurl
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_user.city
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyy_user.tel
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_user.openid
     *
     * @return the value of zyy_user.openid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_user.openid
     *
     * @param openid the value for zyy_user.openid
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_user.nickname
     *
     * @return the value of zyy_user.nickname
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_user.nickname
     *
     * @param nickname the value for zyy_user.nickname
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_user.headimgurl
     *
     * @return the value of zyy_user.headimgurl
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_user.headimgurl
     *
     * @param headimgurl the value for zyy_user.headimgurl
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_user.city
     *
     * @return the value of zyy_user.city
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_user.city
     *
     * @param city the value for zyy_user.city
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyy_user.tel
     *
     * @return the value of zyy_user.tel
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyy_user.tel
     *
     * @param tel the value for zyy_user.tel
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}