package com.zhangyangyang.mapper;

import com.zhangyangyang.pojo.ZyyUser;
import com.zhangyangyang.pojo.ZyyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZyyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    long countByExample(ZyyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int deleteByExample(ZyyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int insert(ZyyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int insertSelective(ZyyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    List<ZyyUser> selectByExample(ZyyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    ZyyUser selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZyyUser record, @Param("example") ZyyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int updateByExample(@Param("record") ZyyUser record, @Param("example") ZyyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int updateByPrimaryKeySelective(ZyyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyy_user
     *
     * @mbg.generated Tue May 08 14:59:51 CST 2018
     */
    int updateByPrimaryKey(ZyyUser record);
}